### ISSUE TITLE
Customising the desktop file

### ISSUE THREAD

**Issue by fossfreedom** [canonical/ubuntu-flavor-installer#30]
In the snapcraft.yaml we define the .desktop file for the flavour - `    desktop: bin/data/flutter_assets/assets/ubuntu-flavor-installer.desktop`

I don't see this .desktop in the repo anywhere - how can we update the file to point to the correct executable i.e. ubuntu-budgie-installer ?

```
 ubuntu-budgie-installer:
    command: bin/ubuntu-budgie-installer
    command-chain: [bin/launcher]
    desktop: bin/data/flutter_assets/assets/ubuntu-flavor-installer.desktop
    environment:
      PATH: $SNAP/usr/bin:$SNAP/bin:$PATH
      LIBGL_DRIVERS_PATH: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/dri
      GIO_MODULE_DIR: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/gio/modules
      LIVE_RUN: 1
      LOG_LEVEL: debug
      SNAP_PYTHON: python3
```
